name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'   

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'    

      - name: Get Flutter dependencies
        run: flutter pub get

      # - name: Check for formatting issues
      #   run: dart format --set-exit-if-changed .

      # - name: Statically analyze Dart code
      #   run: flutter analyze .

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles          
      - name: Export Options file
        env:
         EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
         EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
         echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH

      - name: Build IPA
        run: |
         EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
         if [ -f "$EXPORT_OPTS_PATH" ]; then
          flutter build ipa --target lib/main_car.dart --release --export-options-plist="$EXPORT_OPTS_PATH"
         else
         echo "Error: $EXPORT_OPTS_PATH does not exist."
         exit 1
         fi
      - run: unzip Upload ipa.zip
     
    

      - name: Upload ipa
        uses: actions/upload-artifact@v4
        with:
         name: Upload ipa
         path: /Users/runner/work/flutter_flavor/flutter_flavor/build/ios/ipa/apps/sample_flavor_test.ipa

      - run: unzip Upload ipa.zip   

        

      # - name: Install App Center CLI
      #   run: npm install -g appcenter-cli
        
      # - name: Distribute apk to App Center
      #   uses: akiojin/appcenter-distribute-github-action@v1
      #   with:
      #    token: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
      #    path:  /Users/runner/work/flutter_flavor/flutter_flavor/build/ios/ipa/apps/unzipped_ipa
      #    app: abishekabi/Flutter
      #    mandatory: true
      #    silent: false
      #    group: 'Tests'
      #    release_notes: "Test release"
          
          




  
